#JEKYLL_ENV=production jekyll build
title: DecodeVector
author: Mathscapes Research
url: http://decodevector.mathscapes.xyz/
remote-theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  # - jekyll-paginate
  - jekyll-sitemap

permalink: /sub/:title/
# /:year/:month/:day/:title/
# paginate_path: /:posts/:num/
# paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
    - author
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    author: /member/:name/

sass:
    sass_dir: ./_sass

# Social media
twitter_username: mathscapes
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false
logo: logo.png


# Markdown settings
kramdown:
auto_ids: false
enable_coderay: false
entity_output: as_char
footnote_nr: 1
smart_quotes: lsquo,rsquo,ldquo,rdquo
toc_levels: 1..6
