title: DecodeVector
author: Mathscapes Research
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate_path: /pset/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
    - author
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
    sass_dir: ./_scss
